<template>
  <div class="config-page page-container">
    <header class="page-heading"><div><span class="eyebrow">STEP 2 / TASK CONFIGURATION</span><h1>配置标签与派发任务</h1><p>为已解析数据集定义标注规则、协同方式和质量门禁。</p></div><el-button @click="router.push({ path: '/collection-annotation', query: { datasetId: form.datasetId } })">返回数据导入</el-button></header>
    <div class="steps"><div class="step done"><b>✓</b><span>上传清洗数据集</span></div><div class="line active" /><div class="step active"><b>2</b><span>配置标签与派发任务</span></div><div class="line" /><div class="step"><b>3</b><span>进入专属工作台</span></div></div>

    <el-form ref="formRef" :model="form" :rules="rules" label-position="top" class="config-form">
      <el-row :gutter="16"><el-col :span="15"><el-card shadow="never"><template #header><div class="card-title"><span>任务基础配置</span><el-tag v-if="dataset" type="success">{{ dataset.name }}</el-tag></div></template>
        <el-form-item label="任务名称" prop="name"><el-input v-model="form.name" placeholder="例如：商品文本意图标注" /></el-form-item>
        <el-form-item label="标注数据类型"><el-radio-group v-model="form.mode"><el-radio-button label="TEXT">文本分类</el-radio-button><el-radio-button label="TABLE">表格标注</el-radio-button><el-radio-button label="IMAGE">图片框选</el-radio-button><el-radio-button label="VIDEO">视频时段</el-radio-button></el-radio-group></el-form-item>
        <el-form-item label="选择数据集" prop="datasetId"><el-select v-model="form.datasetId" filterable style="width:100%" placeholder="请选择已解析数据集" @change="loadDataset"><el-option v-for="item in datasets" :key="item.id" :label="`${item.name}（${item.rowCount || 0} 条）`" :value="item.id" /></el-select></el-form-item>
        <el-form-item label="标签体系" prop="labelSchemaId"><div class="schema-row"><el-select v-model="form.labelSchemaId" filterable style="flex:1" placeholder="选择根标签体系" @change="loadLabels"><el-option v-for="item in schemas" :key="item.id" :label="item.name" :value="item.id" /></el-select><el-button @click="schemaDialog=true">新建标签体系</el-button></div></el-form-item>
        <div class="label-list"><div class="section-label">可用标签（{{ labels.length }}）</div><el-tag v-for="label in labels" :key="label.id" closable @close="removeLabel(label)">{{ label.name }} · {{ label.code }}</el-tag><span v-if="!labels.length" class="muted">请选择标签体系</span><el-button link type="primary" @click="labelDialog=true">添加子标签</el-button></div>
      </el-card></el-col><el-col :span="9"><el-card shadow="never"><template #header><span>协同与派发</span></template>
        <el-form-item label="协同模式"><el-radio-group v-model="form.collaborationMode"><el-radio label="SINGLE">单人标注</el-radio><el-radio label="TEAM">多人协同</el-radio></el-radio-group></el-form-item>
        <el-form-item label="标注员 ID"><el-input v-model="form.annotatorIds" placeholder="多个 ID 用逗号分隔，例如 1000,1001" /><div class="helper">后端会按 ID 派发任务并记录审计。</div></el-form-item>
        <el-form-item label="任务说明"><el-input v-model="form.description" type="textarea" :rows="4" placeholder="填写标注边界、示例和交付标准" /></el-form-item>
      </el-card><el-card shadow="never" class="quality-card"><template #header><span>质量抽检规则</span></template><el-form-item label="抽检比例"><el-slider v-model="form.sampleRate" :min="0.05" :max="1" :step="0.05" show-input /><div class="helper">当前抽检 {{ Math.round(form.sampleRate * 100) }}%</div></el-form-item><el-form-item label="审核与仲裁"><el-checkbox v-model="form.reviewRequired">标注提交后必须审核</el-checkbox><el-checkbox v-model="form.arbitrationEnabled">争议进入仲裁</el-checkbox></el-form-item><el-button link type="primary" @click="router.push('/collection-annotation/config/rules')">打开全局规则配置后台</el-button></el-card></el-col></el-row>
      <div class="form-actions"><el-button @click="router.push('/collection-annotation')">保存草稿</el-button><el-button type="primary" :loading="submitting" @click="createAndDispatch">创建任务并进入工作台</el-button></div>
    </el-form>

    <el-dialog v-model="schemaDialog" title="新建标签体系" width="440px"><el-form :model="newSchema" label-position="top"><el-form-item label="名称"><el-input v-model="newSchema.name" /></el-form-item><el-form-item label="编码"><el-input v-model="newSchema.code" /></el-form-item><el-form-item label="说明"><el-input v-model="newSchema.description" type="textarea" /></el-form-item></el-form><template #footer><el-button @click="schemaDialog=false">取消</el-button><el-button type="primary" @click="createSchema">保存</el-button></template></el-dialog>
    <el-dialog v-model="labelDialog" title="添加子标签" width="440px"><el-form :model="newLabel" label-position="top"><el-form-item label="标签名称"><el-input v-model="newLabel.name" /></el-form-item><el-form-item label="标签编码"><el-input v-model="newLabel.code" /></el-form-item></el-form><template #footer><el-button @click="labelDialog=false">取消</el-button><el-button type="primary" @click="createLabel">保存</el-button></template></el-dialog>
  </div>
</template>

<script setup>
import { onMounted, reactive, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { ElMessage } from 'element-plus'
import request from '../utils/request'
import { getActiveDatasetId, setActiveDatasetId } from '../utils/workspaceSync'

const router = useRouter(); const route = useRoute(); const formRef = ref(); const datasets = ref([]); const schemas = ref([]); const labels = ref([]); const dataset = ref(null); const submitting = ref(false); const schemaDialog = ref(false); const labelDialog = ref(false)
const form = reactive({ name: '', datasetId: Number(route.query.datasetId) || null, labelSchemaId: null, mode: 'TABLE', collaborationMode: 'SINGLE', annotatorIds: '', description: '', sampleRate: .1, reviewRequired: true, arbitrationEnabled: true })
const newSchema = reactive({ name: '', code: '', description: '' }); const newLabel = reactive({ name: '', code: '' }); const rules = { name: [{ required: true, message: '请输入任务名称' }], datasetId: [{ required: true, message: '请选择数据集' }], labelSchemaId: [{ required: true, message: '请选择标签体系' }] }
const load = async () => { try { const [d, s] = await Promise.all([request.get('/v1/datasets?page=1&size=100'), request.get('/v1/label-schemas?page=1&size=100')]); datasets.value = (d.records || []).filter(x => x.status === 'PARSED'); schemas.value = s.records || []; const activeId = getActiveDatasetId(); const preferred = datasets.value.find(x => String(x.id) === String(form.datasetId || activeId)) || datasets.value[0]; if (preferred) { form.datasetId = preferred.id; setActiveDatasetId(preferred.id); await loadDataset(preferred.id) } if (!form.labelSchemaId && schemas.value[0]) { form.labelSchemaId = schemas.value[0].id; await loadLabels(form.labelSchemaId) } } catch (e) { ElMessage.error(e.message || '配置数据加载失败') } }
const loadDataset = async id => { dataset.value = datasets.value.find(x => Number(x.id) === Number(id)) || await request.get(`/v1/datasets/${id}`) }
const loadLabels = async id => { labels.value = id ? await request.get(`/v1/label-schemas/${id}/children`) : [] }
const createSchema = async () => { if (!newSchema.name || !newSchema.code) return ElMessage.warning('请填写名称和编码'); try { const saved = await request.post('/v1/label-schemas', newSchema); schemas.value.push(saved); form.labelSchemaId = saved.id; labels.value = []; schemaDialog.value = false; ElMessage.success('标签体系已创建') } catch (e) { ElMessage.error(e.message) } }
const createLabel = async () => { if (!form.labelSchemaId || !newLabel.name || !newLabel.code) return ElMessage.warning('请选择标签体系并填写标签'); try { const label = await request.post('/v1/label-schemas', { ...newLabel, parentId: form.labelSchemaId, tenantId: 1, deleted: 0 }); labels.value.push(label); labelDialog.value = false; ElMessage.success('子标签已添加') } catch (e) { ElMessage.error(e.message) } }
const removeLabel = label => { labels.value = labels.value.filter(x => x.id !== label.id); ElMessage.info('标签已从当前配置移除；全局标签体系未删除') }
const createAndDispatch = async () => { await formRef.value.validate(async valid => { if (!valid) return; submitting.value = true; try { const ruleConfig = JSON.stringify({ mode: form.mode, description: form.description, sampleRate: form.sampleRate, reviewRequired: form.reviewRequired, arbitrationEnabled: form.arbitrationEnabled, labels: labels.value.map(x => x.code) }); const collection = await request.post('/v1/collection-tasks', { name: form.name, sourceType: form.mode === 'TABLE' ? 'DATASET' : form.mode, datasetId: form.datasetId, labelSchemaId: form.labelSchemaId, collaborationMode: form.collaborationMode, annotationRuleJson: ruleConfig }); const annotation = await request.post('/v1/annotation-tasks', { name: form.name, description: form.description, datasetId: form.datasetId, labelSchemaId: form.labelSchemaId }); const ids = form.annotatorIds.split(',').map(x => Number(x.trim())).filter(Number.isFinite); if (ids.length) await request.post(`/v1/annotation-tasks/${annotation.id}/assign`, { annotatorIds: ids }); ElMessage.success('任务已创建并完成派发'); router.push({ path: '/annotation-platform', query: { taskId: annotation.id, collectionTaskId: collection.id, mode: form.mode } }) } catch (e) { ElMessage.error(e.message || '任务创建失败') } finally { submitting.value = false } }) }
onMounted(load)
</script>

<style scoped>
.page-heading,.card-title{display:flex;align-items:center;justify-content:space-between;gap:16px}.page-heading{margin-bottom:20px}.page-heading h1{margin:6px 0;font-size:26px}.page-heading p,.helper,.muted{color:#86909c;font-size:13px}.eyebrow{color:#165dff;font-size:12px;font-weight:700;letter-spacing:.08em}.steps{display:flex;align-items:center;margin-bottom:20px}.step{display:flex;align-items:center;gap:8px;color:#86909c;font-size:14px}.step.active,.step.done{color:#165dff;font-weight:600}.step b{display:grid;place-items:center;width:28px;height:28px;border-radius:50%;background:#f2f3f5}.step.active b,.step.done b{background:#e8f3ff;color:#165dff}.line{height:1px;flex:0 1 120px;margin:0 14px;background:#e5e6eb}.line.active{background:#165dff}.schema-row{display:flex;gap:8px}.label-list{display:flex;align-items:center;gap:8px;flex-wrap:wrap;padding-top:6px}.section-label{width:100%;font-weight:600;margin-bottom:4px}.quality-card{margin-top:16px}.form-actions{display:flex;justify-content:flex-end;gap:12px;margin-top:20px}@media(max-width:900px){.page-heading{align-items:flex-start;flex-direction:column}.line{flex:1}}
</style>
