<template>
  <div class="evaluation-module-page page-container">
    <header class="module-header">
      <div><div class="header-title"><el-icon><TrendCharts /></el-icon><h1>模型准确率评估</h1><el-tag type="success" effect="plain">效果追踪</el-tag></div><p>对每轮预测结果进行量化评估，横向对比模型版本并追溯历史精度变化</p></div>
      <div class="header-actions"><el-button :icon="Setting" @click="router.push('/prediction-evaluation/config#accuracy')">评估规则</el-button><el-button :icon="Download" @click="exportCsv">导出评估报告</el-button></div>
    </header>
    <div class="page-workspace">
      <TaskSidebar v-model="selectedId" v-model:keyword="keyword" :tasks="visibleTasks" :loading="loading" @refresh="loadTasks" />
      <main class="business-content">
        <section class="context-bar surface"><div><small>当前评估任务</small><strong>{{ currentTask?.name }}</strong> <el-tag size="small" effect="plain">{{ currentTask?.model }} {{ currentTask?.version }}</el-tag></div><div class="header-actions"><el-select v-model="evaluationScope" style="width:150px"><el-option label="全部预测样本" value="all"/><el-option label="最近 30 天" value="30d"/><el-option label="异常样本" value="exception"/></el-select><el-button type="primary" :icon="DataAnalysis" :loading="evaluating" @click="runEvaluation">执行准确率评估</el-button></div></section>
        <div class="metric-grid"><article v-for="item in metricCards" :key="item.name" class="metric-card"><div class="metric-head"><span>{{ item.name }}</span><el-tooltip :content="item.help"><el-icon><InfoFilled /></el-icon></el-tooltip></div><strong>{{ item.value }}</strong><small :class="item.good ? 'good' : ''">{{ item.note }}</small></article></div>
        <div class="two-column">
          <section class="surface"><div class="section-head"><div><h2>历史迭代效果趋势</h2><p>准确率、精准率与召回率来自后端评估记录</p></div><el-segmented v-model="range" :options="['近 7 次','近 30 次']" size="small"/></div><div v-if="versionRows.length" class="evaluation-history"><div v-for="row in versionRows" :key="row.id" class="history-row"><span>{{ row.version }}</span><el-progress :percentage="row.accuracyValue" :stroke-width="10"/><b>{{ row.accuracy }}</b></div></div><el-empty v-else description="暂无评估记录，请先执行准确率评估" :image-size="70"/></section>
          <section class="surface"><div class="section-head"><div><h2>预测样本质量</h2><p>本轮指标来自当前选中任务的后端预测结果</p></div></div><el-empty v-if="!currentMetrics" description="暂无预测结果质量指标，请先完成预测或执行评估" :image-size="70"/><template v-else><div class="sample-stats"><span><b>{{ currentAccuracy }}</b>准确率</span><span><b>{{ currentMetrics.mape == null ? '—' : `${Number(currentMetrics.mape).toFixed(2)}%` }}</b>MAPE</span><span><b>{{ currentMetrics.status || '已记录' }}</b>评估状态</span></div></template></section>
        </div>
        <section class="surface table-surface"><div class="section-head"><div><h2>模型版本横向对比</h2><p>统一评估口径下的新旧版本效果台账</p></div><el-button :icon="Plus" @click="compareVisible=true">添加对比版本</el-button></div><el-table :data="versionRows" height="285"><el-table-column prop="version" label="模型版本" width="120"/><el-table-column prop="algorithm" label="算法"/><el-table-column prop="accuracy" label="准确率"/><el-table-column prop="precision" label="精准率"/><el-table-column prop="recall" label="召回率"/><el-table-column prop="mae" label="MAE"/><el-table-column prop="mse" label="MSE"/><el-table-column prop="mape" label="MAPE"/><el-table-column label="评级"><template #default="{row}"><el-tag size="small" :type="row.rating==='优秀'?'success':row.rating==='合格'?'warning':'danger'">{{row.rating}}</el-tag></template></el-table-column><el-table-column label="操作" width="90"><template #default="{row}"><el-button link type="primary" @click="showDetail(row)">详情</el-button></template></el-table-column></el-table></section>
      </main>
    </div>
    <el-dialog v-model="compareVisible" title="添加模型对比版本" width="480px"><el-select v-model="compareVersions" multiple placeholder="选择需要加入的版本" style="width:100%"><el-option v-for="row in versionRows" :key="row.id" :label="`${row.version} · ${row.algorithm}`" :value="row.id"/></el-select><template #footer><el-button @click="compareVisible=false">取消</el-button><el-button type="primary" :disabled="!compareVersions.length" @click="addComparison">加入对比</el-button></template></el-dialog>
  </div>
</template>
<script setup>
import { computed, defineComponent, h, ref, watch } from 'vue'
import { useRouter } from 'vue-router'
import { ElButton, ElEmpty, ElIcon, ElInput, ElMessage, ElTag } from 'element-plus'
import { DataAnalysis, Download, InfoFilled, Plus, Refresh, Search, Setting, TrendCharts } from '@element-plus/icons-vue'
import { useEvaluationTasks } from '../composables/useEvaluationTasks'
import request from '../utils/request'
import '../assets/styles/evaluation-pages.css'
const router=useRouter();const {loading,selectedId,keyword,visibleTasks,currentTask,loadTasks}=useEvaluationTasks();const evaluating=ref(false);const evaluationScope=ref('all');const range=ref('近 7 次');const compareVisible=ref(false);const compareVersions=ref([]);const evaluations=ref([]);const currentMetrics=ref(null)
const latestEvaluation=computed(()=>currentMetrics.value || evaluations.value[0] || null)
const currentAccuracy=computed(()=>currentMetrics.value?.mape == null ? '—' : `${Math.max(0, 100 - Number(currentMetrics.value.mape)).toFixed(1)}%`)
const metricValue=(key, suffix='') => { const value=currentMetrics.value?.[key] ?? currentMetrics.value?.trainingMetrics?.[key]; return value == null ? '—' : `${Number(value).toFixed(2)}${suffix}` }
const isClassification=computed(()=>{const type=String(currentMetrics.value?.taskType || currentMetrics.value?.task_type || currentMetrics.value?.modelType || currentTask.value?.modelType || currentTask.value?.taskType || currentTask.value?.model || '').toLowerCase();return /(classif|logistic|random_forest_classifier|svm_classifier)/.test(type)})
const metricCards=computed(()=>{
  const base=[{name:'综合准确率',value:currentAccuracy.value,note:currentMetrics.value?.status || '来自当前模型指标',good:!!currentMetrics.value,help:'基于当前模型 MAPE 计算的综合准确率'}]
  const typeMetrics=isClassification.value
    ? [{name:'精准率',value:metricValue('precision'),note:'来自后端分类评估记录',good:currentMetrics.value?.precision != null,help:'预测为正类的样本中实际为正类的比例'},{name:'召回率',value:metricValue('recall'),note:'来自后端分类评估记录',good:currentMetrics.value?.recall != null,help:'实际正类样本中被正确识别的比例'}]
    : [{name:'R²',value:metricValue('r2'),note:'来自后端回归/时序评估记录',good:currentMetrics.value?.r2 != null || currentMetrics.value?.trainingMetrics?.r2 != null,help:'决定系数，越接近 1 表示拟合效果越好'},{name:'MSE',value:metricValue('mse'),note:'来自后端回归/时序评估记录',good:currentMetrics.value?.mse != null,help:'均方误差，越低越好'}]
  return [...base,...typeMetrics,{name:'MAE',value:metricValue('mae'),note:'来自当前模型评估指标',good:!!currentMetrics.value,help:'平均绝对误差，越低越好'},{name:'RMSE',value:metricValue('rmse'),note:'来自当前模型评估指标',good:!!currentMetrics.value,help:'均方根误差，越低越好'},{name:'MAPE',value:metricValue('mape','%'),note:'来自当前模型评估指标',good:!!currentMetrics.value,help:'平均绝对百分比误差'}]
})
const versionRows=computed(()=>evaluations.value.map((row,index)=>({id:row.id,version:`评估 #${row.id}`,algorithm:row.algorithm || '未知算法',accuracy:row.accuracyScore == null ? '—' : `${(row.accuracyScore*100).toFixed(1)}%`,accuracyValue:row.accuracyScore == null ? 0 : Math.max(0,Math.min(100,row.accuracyScore*100)),precision:'—',recall:'—',mae:row.mae ?? '—',mse:'—',mape:row.mape == null ? '—' : `${row.mape}%`,rating:row.status || '已记录',createdAt:row.createdAt})))
async function loadEvaluations(){ evaluations.value=[]; currentMetrics.value=null; if(!selectedId.value) return; try { const [history, metricsData] = await Promise.all([request.get(`/v1/predictions/${selectedId.value}/evaluation-history`), request.get(`/v1/predictions/${selectedId.value}/metrics`)]); evaluations.value=history || []; currentMetrics.value=metricsData || null } catch(e){ ElMessage.error(`评估记录加载失败：${e.message || '后端接口不可用'}`) } }
watch(selectedId, loadEvaluations, { immediate:true })
async function runEvaluation(){if(!selectedId.value)return ElMessage.warning('请选择预测任务');evaluating.value=true;try{await request.post(`/v1/predictions/${selectedId.value}/evaluate`);await loadEvaluations();ElMessage.success('准确率评估完成，结果已保存到后端')}catch(e){ElMessage.error(`评估失败：${e.message || '后端接口不可用'}`)}finally{evaluating.value=false}}
function exportCsv(){const body='\uFEFF指标,当前值,评估结论\n'+metrics.value.map(i=>`${i.name},${i.value},${i.note}`).join('\n');const url=URL.createObjectURL(new Blob([body],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`${currentTask.value?.name}-准确率评估.csv`;a.click();URL.revokeObjectURL(url)}
function showDetail(row){ElMessage.info(`${row.version}：准确率 ${row.accuracy}，MAPE ${row.mape}`)}function addComparison(){compareVisible.value=false;ElMessage.success(`已加入 ${compareVersions.value.length} 个后端评估记录`)}
const TaskSidebar=defineComponent({props:{modelValue:[String,Number],keyword:String,tasks:Array,loading:Boolean},emits:['update:modelValue','update:keyword','refresh'],setup(p,{emit}){return()=>h('aside',{class:'task-sidebar'},[h('div',{class:'section-head'},[h('div',[h('h2','模型评估任务'),h('p',`${p.tasks.length} 个任务`)]),h(ElButton,{circle:true,icon:Refresh,loading:p.loading,onClick:()=>emit('refresh')})]),h(ElInput,{modelValue:p.keyword,'onUpdate:modelValue':v=>emit('update:keyword',v),prefixIcon:Search,placeholder:'搜索任务或模型版本',clearable:true}),h('div',{class:'task-list'},p.tasks.length?p.tasks.map(t=>h('button',{class:['task-item',{active:p.modelValue===t.id}],onClick:()=>emit('update:modelValue',t.id)},[h('div',{class:'task-head'},[h('b',t.name),h(ElTag,{size:'small',type:t.status==='已完成'?'success':t.status==='待优化'?'warning':'info'},()=>t.status)]),h('div',{class:'task-meta'},[h('span',t.model),h('span',t.version)]),h('div',{class:'task-stats'},[h('span',`准确率 ${t.accuracy??'待评估'}${t.accuracy?'%':''}`),h('span',`MAPE ${t.mape??'--'}${t.mape?'%':''}`)])])):h(ElEmpty,{imageSize:60,description:'暂无任务'})),h('div',{class:'task-source'},'上游：模块 3 预测结果 · 模块 4 异常数据')])}})
</script>
<style scoped>.metric-grid{grid-template-columns:repeat(3,minmax(0,1fr))}.evaluation-module-page,.business-content,.metric-grid,.surface{min-width:0}.axis-labels{display:flex;justify-content:space-between;font-size:10px;color:#86909c}.sample-ring{width:175px;height:175px;margin:8px auto 20px;border-radius:50%;background:conic-gradient(#165dff 0 96.8%,#f2f3f5 96.8%);display:grid;place-items:center;position:relative}.sample-ring:before{content:"";position:absolute;width:128px;height:128px;border-radius:50%;background:#fff}.sample-ring div{position:relative;text-align:center}.sample-ring b,.sample-ring span{display:block}.sample-ring b{font-size:25px}.sample-ring span{font-size:11px;color:#86909c;margin-top:5px}.sample-stats{display:grid;grid-template-columns:repeat(3,1fr);border-top:1px solid #f2f3f5;padding-top:14px}.sample-stats span{text-align:center;color:#86909c;font-size:10px}.sample-stats b{display:block;color:#1d2129;font-size:14px;margin-bottom:4px}@media(max-width:1280px){.metric-grid{grid-template-columns:repeat(3,minmax(0,1fr))}}@media(max-width:820px){.metric-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:520px){.metric-grid{grid-template-columns:1fr}}
</style>
