<template>
  <div class="evaluation-module-page page-container">
    <header class="module-header"><div><div class="header-title"><el-icon><Monitor /></el-icon><h1>模型性能监控中心</h1><span class="live"><i></i>实时监控中</span></div><p>监控训练、预测和推理全周期性能，及时识别退化、卡顿与资源异常</p></div><div class="header-actions"><el-button :icon="Setting" @click="router.push('/prediction-evaluation/config#performance')">监控策略</el-button><el-button :icon="Bell" @click="alertVisible=true">告警记录</el-button></div></header>
    <div class="page-workspace"><TaskList/><main class="business-content">
      <section class="context-bar surface"><div><small>当前监控模型</small><strong>{{currentTask?.name}} · {{currentTask?.version}}</strong></div><div class="header-actions"><el-tag type="success">服务正常</el-tag><el-button :icon="Refresh" :loading="refreshing" @click="refreshMetrics">刷新监控</el-button></div></section>
      <div class="metric-grid"><article v-for="m in performanceMetrics" :key="m.name" class="metric-card"><div class="metric-head"><span>{{m.name}}</span><el-icon><component :is="m.icon"/></el-icon></div><strong>{{m.value}}</strong><small :class="m.good?'good':''">{{m.note}}</small></article></div>
      <div class="two-column"><section class="surface"><div class="section-head"><div><h2>推理延迟与吞吐量</h2><p>运行采样接口接入后展示</p></div><el-select v-model="range" style="width:120px"><el-option label="近 24 小时" value="24h"/><el-option label="近 7 天" value="7d"/></el-select></div><div v-if="samples.length" class="chart-summary"><div><span>最新延迟</span><b>{{num(samples[0]?.latencyMs)}} ms</b></div><div><span>峰值 QPS</span><b>{{num(monitoring.peakQps)}}</b></div></div><el-empty v-else description="暂无运行采样数据" :image-size="70"/></section><section class="surface"><div class="section-head"><div><h2>资源占用率</h2><p>由后端 JVM、主机资源采样接口提供</p></div><el-tag v-if="resources.length" type="success" effect="plain">实时采样</el-tag></div><div v-if="resources.length" class="resource-list"><div v-for="resource in resources" :key="resource.name" class="resource-row"><span>{{resource.name}}</span><el-progress :percentage="Math.min(100, resource.value)" :color="resource.color"/><b>{{num(resource.value)}}%</b></div></div><el-empty v-else description="暂无资源采样数据" :image-size="70"/></section></div>
      <div class="equal-column"><section class="surface"><div class="section-head"><div><h2>连续预测误差波动</h2><p>当前采样记录的延迟变化</p></div></div><div v-if="bars.length" class="bar-chart compact"><i v-for="(v,i) in bars" :key="i" :style="{height:v+'%',background:v>75?'#ffb65d':'#86adff'}"></i></div><el-empty v-else description="暂无连续采样记录" :image-size="70"/></section><section class="surface"><div class="section-head"><div><h2>运行异常事件</h2><p>性能阈值和运行失败自动生成</p></div><el-button link type="primary" @click="alertVisible=true">查看全部</el-button></div><div v-if="events.length" class="list-rows"><div v-for="e in events" :key="e.id"><span class="number-icon"><el-icon><WarningFilled/></el-icon></span><div><b>{{e.title}}</b><small>{{e.description}}</small></div><el-tag size="small" :type="e.status==='RESOLVED'?'success':'warning'">{{e.status}}</el-tag></div></div><el-empty v-else description="暂无运行异常事件" :image-size="70"/></section></div>
      <section class="surface table-surface"><div class="section-head"><div><h2>训练与推理运行记录</h2><p>异常卡顿、推理超时和训练失败统计</p></div></div><el-table :data="runs" height="260" empty-text="暂无运行记录"><el-table-column prop="id" label="运行 ID"/><el-table-column prop="type" label="阶段"/><el-table-column prop="duration" label="耗时"/><el-table-column prop="latency" label="平均延迟"/><el-table-column prop="resource" label="峰值资源"/><el-table-column prop="time" label="发生时间" min-width="150"/><el-table-column label="状态"><template #default="{row}"><el-tag size="small" :type="row.status==='成功'?'success':'danger'">{{row.status}}</el-tag></template></el-table-column></el-table></section>
    </main></div><el-drawer v-model="alertVisible" title="性能告警记录" size="460px"><el-timeline><el-timeline-item v-for="e in events" :key="e.id" :timestamp="e.detectedAt" :type="e.status==='RESOLVED'?'success':'warning'"><b>{{e.title}}</b><p>{{e.description}}</p></el-timeline-item><el-empty v-if="!events.length" description="暂无告警" :image-size="70"/></el-timeline></el-drawer>
  </div>
</template>
<script setup>
import { computed, defineComponent, h, markRaw, onBeforeUnmount, onMounted, ref, watch } from 'vue';import { useRouter } from 'vue-router';import { ElButton,ElEmpty,ElInput,ElMessage,ElTag } from 'element-plus';import { Bell,Cpu,Monitor,Refresh,Search,Setting,Stopwatch,TrendCharts,WarningFilled } from '@element-plus/icons-vue';import { useEvaluationTasks } from '../composables/useEvaluationTasks';import request from '../utils/request';import '../assets/styles/evaluation-pages.css'
const router=useRouter();const {loading,selectedId,keyword,visibleTasks,currentTask,loadTasks}=useEvaluationTasks();const alertVisible=ref(false),refreshing=ref(false),range=ref('24h');const monitoring=ref({}),samples=ref([]),events=ref([]);let monitorTimer=null;let monitorRequestInFlight=false;const num=v=>v==null?'—':Number(v).toFixed(2);const performanceMetrics=computed(()=>[{name:'采样成功率',value:monitoring.value.sampleCount?`${((monitoring.value.successCount||0)/monitoring.value.sampleCount*100).toFixed(1)}%`:'—',note:`${monitoring.value.sampleCount||0} 条采样记录`,good:!!monitoring.value.sampleCount,icon:markRaw(Stopwatch)},{name:'平均推理延迟',value:monitoring.value.sampleCount?`${num(monitoring.value.averageLatencyMs)} ms`:'—',note:'来自性能采样',good:!!monitoring.value.sampleCount,icon:markRaw(Monitor)},{name:'峰值 QPS',value:monitoring.value.sampleCount?num(monitoring.value.peakQps):'—',note:'来自吞吐采样',good:!!monitoring.value.sampleCount,icon:markRaw(TrendCharts)},{name:'运行失败数',value:String(monitoring.value.failureCount||0),note:'来自运行状态采样',good:!monitoring.value.failureCount,icon:markRaw(Cpu)}]);const bars=computed(()=>samples.value.map(x=>Math.min(100,Number(x.latencyMs||0)/2)).slice(-32));const resources=computed(()=>{const s=monitoring.value;return [{name:'CPU',value:Number(s.averageCpuPercent||0),color:'#165dff'},{name:'内存',value:Number(s.averageMemoryPercent||0),color:'#00b42a'},{name:'GPU',value:Number(s.averageGpuPercent||0),color:'#722ed1'}].filter(x=>x.value>0)});const runs=computed(()=>samples.value.slice().reverse().map(x=>({id:x.id,type:x.sampleType,duration:x.durationMs==null?'—':`${x.durationMs} ms`,latency:x.latencyMs==null?'—':`${x.latencyMs} ms`,resource:x.cpuPercent==null?'—':`CPU ${x.cpuPercent}%`,time:x.sampledAt,status:x.status==='SUCCESS'?'成功':'失败'})));async function loadMonitoring(silent=false){if(monitorRequestInFlight)return;monitorRequestInFlight=true;try{const taskQuery=selectedId.value?`&taskId=${selectedId.value}`:'';const [summary,rows,alerts]=await Promise.all([request.get(`/v1/predictions/monitoring/summary?minutes=${range.value==='7d'?10080:1440}${taskQuery}`),request.get(`/v1/predictions/monitoring/samples?minutes=${range.value==='7d'?10080:1440}${taskQuery}`),request.get(`/v1/predictions/monitoring/alerts?limit=100${selectedId.value?`&taskId=${selectedId.value}`:''}`)]);monitoring.value=summary||{};samples.value=Array.isArray(rows)?rows:samples.value;events.value=Array.isArray(alerts)?alerts:events.value}catch(e){if(!silent){monitoring.value={};samples.value=[];events.value=[];ElMessage.error(`监控数据加载失败：${e.message||'后端接口不可用'}`)}}finally{monitorRequestInFlight=false}}watch([selectedId,range],()=>loadMonitoring(false),{immediate:true});async function refreshMetrics(){refreshing.value=true;try{await request.post(`/v1/predictions/monitoring/samples/system${selectedId.value?`?taskId=${selectedId.value}`:''}`);await Promise.all([loadTasks(),loadMonitoring(false)]);ElMessage.success('性能监控数据已刷新')}finally{refreshing.value=false}}
onMounted(() => { monitorTimer = window.setInterval(() => loadMonitoring(true), 1000) })
onBeforeUnmount(() => { if (monitorTimer) window.clearInterval(monitorTimer) })
const TaskList=defineComponent({setup(){return()=>h('aside',{class:'task-sidebar'},[h('div',{class:'section-head'},[h('div',[h('h2','监控模型列表'),h('p',`${visibleTasks.value.length} 个运行模型`)]),h(ElButton,{circle:true,icon:Refresh,loading:loading.value,onClick:loadTasks})]),h(ElInput,{modelValue:keyword.value,'onUpdate:modelValue':v=>keyword.value=v,prefixIcon:Search,placeholder:'搜索模型',clearable:true}),h('div',{class:'task-list'},visibleTasks.value.length?visibleTasks.value.map(t=>{const latest=samples.value.find(x=>x.predictionTaskId===t.id);return h('button',{class:['task-item',{active:selectedId.value===t.id}],onClick:()=>selectedId.value=t.id},[h('div',{class:'task-head'},[h('b',t.name),h(ElTag,{size:'small',type:'success'},()=> '运行中')]),h('div',{class:'task-meta'},[h('span',t.model),h('span',t.version)]),h('div',{class:'task-stats'},[h('span',latest?.latencyMs!=null?`延迟 ${num(latest.latencyMs)}ms`:'暂无延迟采样'),h('span',latest?.status||'暂无运行状态')])])}):h(ElEmpty,{imageSize:60,description:'暂无模型'})),h('div',{class:'task-source'},'性能数据由后端采样接口提供，异常事件自动生成告警')])}})
</script><style scoped>.live{display:inline-flex;align-items:center;gap:6px;color:#00a825;font-size:11px}.live i{width:7px;height:7px;border-radius:50%;background:#00b42a;box-shadow:0 0 0 3px rgba(0,180,42,.12)}.axis-labels{display:flex;justify-content:space-between;color:#86909c;font-size:10px;margin-top:7px}</style>
