<template>
  <div class="config-page page-container">
    <header class="page-heading"><div><div class="eyebrow">FORECASTING ENGINE / GOVERNANCE</div><h1>需求预测引擎模块及模型管理后台</h1><p>统一管理模型体系、深度学习框架环境、参数模板、模型版本生命周期和 A/B 测试规则。</p></div><el-button @click="router.push('/prediction-engine')">返回市场需求预测引擎</el-button></header>
    <el-tabs v-model="active" class="config-tabs">
      <el-tab-pane label="模型库与参数模板" name="models">
        <section class="panel"><div class="panel-title"><div><b>四类预测模型库</b><small>时间序列、回归、分类、深度序列模型统一维护</small></div><el-button type="primary" @click="openAlgorithm">新增模型</el-button></div><el-table v-loading="loading" :data="algorithms" stripe><el-table-column prop="algorithmName" label="模型名称" min-width="170"/><el-table-column prop="algorithmType" label="算法编码" min-width="190"/><el-table-column prop="algorithmFamily" label="模型体系" width="130"/><el-table-column prop="taskType" label="任务类型" width="120"/><el-table-column label="默认参数" min-width="240"><template #default="{ row }"><code>{{ row.defaultParams || '{}' }}</code></template></el-table-column><el-table-column label="状态" width="90"><template #default="{ row }"><el-tag :type="row.isEnabled ? 'success' : 'info'">{{ row.isEnabled ? '启用' : '停用' }}</el-tag></template></el-table-column><el-table-column label="操作" width="170" fixed="right"><template #default="{ row }"><el-button link @click="editAlgorithm(row)">编辑</el-button><el-button link :type="row.isEnabled ? 'warning' : 'success'" @click="toggleAlgorithm(row)">{{ row.isEnabled ? '停用' : '启用' }}</el-button></template></el-table-column></el-table></section>
      </el-tab-pane>
      <el-tab-pane label="训练框架与资源" name="runtime">
        <section class="panel"><div class="panel-title"><div><b>TensorFlow / PyTorch 运行环境</b><small>训练环境状态由后端深度学习引擎健康检查返回</small></div><el-button :loading="loadingStatus" @click="loadFrameworkStatus">刷新状态</el-button></div><div class="framework-grid"><div v-for="(item, name) in frameworkItems" :key="name" class="framework-card"><div><b>{{ name }}</b><el-tag size="small" :type="item.reachable ? 'success' : 'info'">{{ item.reachable ? '在线' : '待连接' }}</el-tag></div><span>{{ item.reachable ? '可提交训练任务' : '使用本地算法或启动 Python 引擎后可训练' }}</span><small>运行状态：{{ item.status }}</small></div></div><el-form :model="config" label-position="top" class="runtime-form"><el-row :gutter="16"><el-col :span="8"><el-form-item label="默认训练框架"><el-select v-model="config.framework" style="width:100%"><el-option label="TensorFlow" value="TensorFlow"/><el-option label="PyTorch" value="PyTorch"/></el-select></el-form-item></el-col><el-col :span="8"><el-form-item label="GPU 资源策略"><el-select v-model="config.resourcePolicy" style="width:100%"><el-option label="自动分配" value="AUTO"/><el-option label="CPU 优先" value="CPU"/><el-option label="GPU 优先" value="GPU"/></el-select></el-form-item></el-col><el-col :span="8"><el-form-item label="训练队列并发数"><el-input-number v-model="config.queueConcurrency" :min="1" :max="200"/></el-form-item></el-col></el-row><el-row :gutter="16"><el-col :span="8"><el-form-item label="TensorFlow 版本"><el-input v-model="config.tensorflowVersion"/></el-form-item></el-col><el-col :span="8"><el-form-item label="PyTorch 版本"><el-input v-model="config.pytorchVersion"/></el-form-item></el-col><el-col :span="8"><el-form-item label="CUDA 版本"><el-input v-model="config.cudaVersion"/></el-form-item></el-col></el-row></el-form></section>
      </el-tab-pane>
      <el-tab-pane label="模型版本生命周期" name="versions">
        <section class="panel"><div class="panel-title"><div><b>历史模型版本</b><small>版本归档、锁定、回滚和线上切换均写入后端</small></div><el-button @click="loadModels">刷新</el-button></div><el-table :data="models" stripe><el-table-column prop="modelName" label="模型名称" min-width="170"/><el-table-column prop="algorithmType" label="算法" min-width="140"/><el-table-column prop="versionNumber" label="版本" width="80"/><el-table-column prop="trainingSamples" label="训练样本" width="100"/><el-table-column prop="mape" label="MAPE" width="90"/><el-table-column label="状态" width="110"><template #default="{ row }"><el-tag :type="versionType(row.status)">{{ row.isProduction ? '生产版本' : row.status || 'ACTIVE' }}</el-tag></template></el-table-column><el-table-column label="操作" min-width="260" fixed="right"><template #default="{ row }"><el-button link :disabled="row.status === 'LOCKED'" @click="modelAction(row, 'archive')">归档</el-button><el-button link @click="modelAction(row, row.status === 'LOCKED' ? 'unlock' : 'lock')">{{ row.status === 'LOCKED' ? '解锁' : '锁定' }}</el-button><el-button link type="primary" @click="modelAction(row, 'rollback')">回滚上线</el-button></template></el-table-column></el-table></section>
      </el-tab-pane>
      <el-tab-pane label="A/B 测试规则" name="ab">
        <section class="panel"><div class="panel-title"><div><b>A/B 测试体系配置</b><small>配置全局指标权重、流量分配、自动择优和报告留存规则</small></div></div><el-form :model="config" label-position="top"><el-row :gutter="16"><el-col :span="8"><el-form-item label="Champion 流量 (%)"><el-input-number v-model="config.championTraffic" :min="0" :max="100"/></el-form-item></el-col><el-col :span="8"><el-form-item label="Challenger 流量 (%)"><el-input-number v-model="config.challengerTraffic" :min="0" :max="100"/></el-form-item></el-col><el-col :span="8"><el-form-item label="报告留存天数"><el-input-number v-model="config.reportRetentionDays" :min="1" :max="3650"/></el-form-item></el-col></el-row><el-divider content-position="left">自动择优指标权重</el-divider><el-row :gutter="16"><el-col :span="6"><el-form-item label="准确率"><el-input-number v-model="config.accuracyWeight" :min="0" :max="1" :step=".05"/></el-form-item></el-col><el-col :span="6"><el-form-item label="MAE"><el-input-number v-model="config.maeWeight" :min="0" :max="1" :step=".05"/></el-form-item></el-col><el-col :span="6"><el-form-item label="RMSE"><el-input-number v-model="config.rmseWeight" :min="0" :max="1" :step=".05"/></el-form-item></el-col><el-col :span="6"><el-form-item label="MAPE"><el-input-number v-model="config.mapeWeight" :min="0" :max="1" :step=".05"/></el-form-item></el-col></el-row><el-form-item label="低于阈值自动触发 Retraining"><el-switch v-model="config.autoRetrain"/></el-form-item><el-form-item label="自动重训练准确率阈值"><el-input-number v-model="config.accuracyThreshold" :min="0" :max="1" :step=".01"/></el-form-item></el-form></section>
      </el-tab-pane>
    </el-tabs>
    <div class="actions"><el-button @click="restore">恢复默认</el-button><el-button @click="snapshot">保存版本快照</el-button><el-button type="primary" :loading="saving" @click="save">保存配置</el-button></div>

    <el-dialog v-model="algorithmVisible" :title="algorithmForm.id ? '编辑模型配置' : '新增模型配置'" width="620px"><el-form :model="algorithmForm" label-position="top"><el-row :gutter="14"><el-col :span="12"><el-form-item label="算法名称"><el-input v-model="algorithmForm.algorithmName" placeholder="例如：LSTM 深度序列预测"/></el-form-item></el-col><el-col :span="12"><el-form-item label="算法编码"><el-input v-model="algorithmForm.algorithmType" placeholder="例如：LSTM_DL"/></el-form-item></el-col><el-col :span="12"><el-form-item label="模型体系"><el-select v-model="algorithmForm.algorithmFamily" style="width:100%"><el-option label="时间序列" value="TIME_SERIES"/><el-option label="回归预测" value="REGRESSION"/><el-option label="分类预测" value="CLASSIFICATION"/><el-option label="深度学习" value="DEEP_LEARNING"/></el-select></el-form-item></el-col><el-col :span="12"><el-form-item label="任务类型"><el-select v-model="algorithmForm.taskType" style="width:100%"><el-option label="回归" value="REGRESSION"/><el-option label="分类" value="CLASSIFICATION"/><el-option label="序列" value="SEQUENCE"/></el-select></el-form-item></el-col></el-row><el-form-item label="默认超参数 JSON"><el-input v-model="algorithmForm.defaultParams" type="textarea" :rows="4" placeholder='{"epochs":100,"learning_rate":0.001}'/></el-form-item><el-form-item label="优先级"><el-input-number v-model="algorithmForm.priority" :min="0" :max="999"/></el-form-item></el-form><template #footer><el-button @click="algorithmVisible=false">取消</el-button><el-button type="primary" :loading="algorithmSaving" @click="saveAlgorithm">保存模型配置</el-button></template></el-dialog>
  </div>
</template>

<script setup>
import { onMounted, reactive, ref, computed } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { useRouter } from 'vue-router'
import request from '../utils/request'
const router = useRouter(); const active = ref('models'); const loading = ref(false); const loadingStatus = ref(false); const saving = ref(false); const algorithmSaving = ref(false); const algorithmVisible = ref(false); const algorithms = ref([]); const models = ref([]); const frameworkStatus = reactive({}); const defaults = { framework:'PyTorch', resourcePolicy:'AUTO', queueConcurrency:10, tensorflowVersion:'2.x', pytorchVersion:'2.x', cudaVersion:'12.x', championTraffic:50, challengerTraffic:50, reportRetentionDays:90, accuracyWeight:.4, maeWeight:.2, rmseWeight:.2, mapeWeight:.2, autoRetrain:false, accuracyThreshold:.8 }; const config = reactive({ ...defaults }); const algorithmForm = reactive({ id:null, algorithmName:'', algorithmType:'', algorithmFamily:'TIME_SERIES', taskType:'REGRESSION', defaultParams:'{}', priority:10, isEnabled:true, isDefault:false });
const frameworkItems = computed(() => {
  const engineReachable = Boolean(frameworkStatus.pythonEngineReachable)
  const framework = name => frameworkStatus[name.toLowerCase()] || {
    enabled: Boolean(frameworkStatus.pythonEngineEnabled),
    reachable: engineReachable,
    status: engineReachable ? 'ONLINE' : 'NOT_CONFIGURED'
  }
  return { TensorFlow: framework('tensorflow'), PyTorch: framework('pytorch') }
})
const versionType = s => ({ PRODUCTION:'success', ACTIVE:'info', LOCKED:'warning', ARCHIVED:'info' }[s] || 'info')
const loadAlgorithms = async () => { loading.value=true; try { algorithms.value=await request.get('/v1/prediction-admin/algorithms') } catch(e){ElMessage.error(e.message||'模型库加载失败')} finally{loading.value=false} }
const loadModels = async () => { try { models.value=await request.get('/v1/predictions/models') } catch(e){ElMessage.error(e.message||'模型版本加载失败')} }
const loadFrameworkStatus = async () => { loadingStatus.value=true; try { Object.assign(frameworkStatus, await request.get('/v1/prediction-admin/framework-status')) } catch(e){ElMessage.error(e.message||'框架状态加载失败')} finally{loadingStatus.value=false} }
const loadConfig = async () => { try { const saved=await request.get('/v1/system-config/prediction-engine'); if(saved?.configJson) Object.assign(config, JSON.parse(saved.configJson)) } catch(e){} }
const save = async () => { saving.value=true; try { await request.put('/v1/system-config/prediction-engine', JSON.stringify(config), { headers:{'Content-Type':'application/json'} }); ElMessage.success('预测引擎后台配置已保存') } catch(e){ElMessage.error(e.message||'配置保存失败')} finally{saving.value=false} }
const snapshot = async () => { try { await request.post('/v1/system-config/prediction-engine/snapshots', JSON.stringify(config), { headers:{'Content-Type':'application/json'} }); ElMessage.success('配置快照已保存') } catch(e){ElMessage.error(e.message||'快照保存失败')} }
const restore = () => { Object.assign(config, defaults); ElMessage.info('已恢复默认值，请点击保存配置') }
const openAlgorithm = () => { Object.assign(algorithmForm, { id:null, algorithmName:'', algorithmType:'', algorithmFamily:'TIME_SERIES', taskType:'REGRESSION', defaultParams:'{}', priority:10, isEnabled:true, isDefault:false }); algorithmVisible.value=true }
const editAlgorithm = row => { Object.assign(algorithmForm, row); algorithmVisible.value=true }
const saveAlgorithm = async () => { if(!algorithmForm.algorithmName||!algorithmForm.algorithmType) return ElMessage.warning('请填写算法名称和编码'); algorithmSaving.value=true; try { if(algorithmForm.id) await request.put(`/v1/prediction-admin/algorithms/${algorithmForm.id}`, algorithmForm); else await request.post('/v1/prediction-admin/algorithms', algorithmForm); algorithmVisible.value=false; await loadAlgorithms(); ElMessage.success('模型配置已保存') } catch(e){ElMessage.error(e.message||'模型配置保存失败')} finally{algorithmSaving.value=false} }
const toggleAlgorithm = async row => { try { await request.post(`/v1/prediction-admin/algorithms/${row.id}/${row.isEnabled?'disable':'enable'}`); await loadAlgorithms(); ElMessage.success('模型状态已更新') } catch(e){ElMessage.error(e.message||'模型状态更新失败')} }
const modelAction = async (row, action) => { try { await ElMessageBox.confirm(`确认对 ${row.modelName || '该模型'} 执行${action === 'archive' ? '归档' : action === 'lock' ? '锁定' : action === 'unlock' ? '解锁' : '回滚上线'}？`, '模型版本操作'); await request.post(`/v1/prediction-admin/models/${row.id}/${action}`); await loadModels(); ElMessage.success('模型版本操作已完成') } catch(e) { if(e !== 'cancel' && e !== 'close') ElMessage.error(e.message||'模型操作失败') } }
onMounted(async()=>{ await Promise.all([loadAlgorithms(), loadModels(), loadFrameworkStatus(), loadConfig()]) })
</script>

<style scoped>.page-heading,.actions,.panel-title{display:flex;align-items:center;justify-content:space-between;gap:16px}.page-heading{margin-bottom:18px}.page-heading h1{margin:6px 0 8px;font-size:26px}.page-heading p,.eyebrow,.panel-title small{color:#86909c;font-size:13px}.eyebrow{color:#165dff;font-weight:700;letter-spacing:.08em;font-size:12px}.panel{background:#fff;border:1px solid #e5e6eb;border-radius:8px;padding:18px;box-shadow:0 1px 4px rgba(0,0,0,.04)}.panel-title{margin-bottom:16px}.panel-title b{font-size:16px}.panel-title small{display:block;margin-top:5px;font-size:12px}.actions{justify-content:flex-end;margin-top:18px}.framework-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:14px;margin-bottom:24px}.framework-card{padding:18px;background:#f7f8fa;border:1px solid #e5e6eb;border-radius:6px}.framework-card>div{display:flex;align-items:center;justify-content:space-between}.framework-card b{font-size:17px}.framework-card span,.framework-card small{display:block;margin-top:10px;color:#4e5969;font-size:13px}.framework-card small{color:#86909c;font-size:12px}code{color:#4e5969;font-size:12px;word-break:break-all}.runtime-form{padding-top:8px}@media(max-width:700px){.page-heading{align-items:flex-start;flex-direction:column}.framework-grid{grid-template-columns:1fr}}
</style>
